CREATE TABLE keys (
  id    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key   CHAR (1) UNIQUE NOT NULL,
  value VARCHAR (10) UNIQUE NOT NULL
);

INSERT INTO keys (key, value) VALUES ('0', '零');
INSERT INTO keys (key, value) VALUES ('1', 'Uno');
INSERT INTO keys (key, value) VALUES ('2', 'Two');
INSERT INTO keys (key, value) VALUES ('3', 'तीन');
INSERT INTO keys (key, value) VALUES ('4', 'أربعة');
INSERT INTO keys (key, value) VALUES ('5', 'Cinco');
INSERT INTO keys (key, value) VALUES ('6', 'ছয়');
INSERT INTO keys (key, value) VALUES ('7', 'семь');
INSERT INTO keys (key, value) VALUES ('8', '八');
INSERT INTO keys (key, value) VALUES ('9', 'ਨੌਂ');
